services:
  ecommerce-db-auth:
    image: postgres:16.2-alpine3.19
    container_name: ecommerce-db-auth
    ports:
      - "4848:5432"
    environment:
      POSTGRES_USER: "ecommercedbauth"
      POSTGRES_PASSWORD: "52e91258b667c2b01de5"
      POSTGRES_DB: "ecommercedbauth"
    volumes:
      - pg-database:/var/lib/postgresql/data
  ecommerce-db-product:
    image: mysql:latest
    container_name: ecommerce-db-product
    ports:
      - "4849:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "ec31d315916485460cadb7fc58c90118795ddeccb75147e5d38d4dbcde433c1c"
      MYSQL_DATABASE: "ecommercedbproduct"
    volumes:
      - mysql-database:/var/lib/mysql
  ecommerce-users-api-service:
    image: pzwitthawasdev/ecommerce-users-api-service:latest
    container_name: ecommerce-users-api-service
    ports:
      - "4000:8080"
    environment:
      ConnectionStrings__PostgresSQLConnection: "Host=ecommerce-db-auth;Port=5432;Database=ecommercedbauth;Username=ecommercedbauth;Password=52e91258b667c2b01de5"
    depends_on:
      - ecommerce-db-auth
  ecommerce-product-api-service:
    image: pzwitthawasdev/ecommerce-products-api-service:latest
    container_name: ecommerce-product-api-service
    ports:
      - "4001:8080"
    environment:
      ConnectionStrings__MySqlConnection: "server=ecommerce-db-product;port=3306;database=ecommercedbproduct;user=root;password=ec31d315916485460cadb7fc58c90118795ddeccb75147e5d38d4dbcde433c1c"
    depends_on:
      - ecommerce-db-product
volumes:
  pg-database:
    driver: local
  mysql-database:
    driver: local
  